import {Dimensions, StyleSheet} from 'react-native';
import {COLORS} from 'src/constants';
const screenHeight = Dimensions.get('screen').height;
const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 40,
        backgroundColor: '#f5f5f5',
      },
      header: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
      },
      categoryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: screenHeight*0.02,
        borderRadius: 30,
        marginBottom: screenHeight *0.02,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
        elevation: 5,
        height: screenHeight *0.06,
      },
      colorIndicator: {
        width: 20,
        height: 20,
        borderRadius: 10,
        marginRight: 10,
      },
      categoryName: {
        fontSize: 16,
      },
      plusIcon: {
        backgroundColor: '#007BFF',
        padding: 15,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        bottom: 20,
        right: 20,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
        elevation: 5,
      },
      rightActionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        height: screenHeight *0.06,
      },
      actionButton: {
        justifyContent: 'center',
        alignItems: 'center',
        width: screenWidth * 0.15,
        height: '100%',
        backgroundColor: '#fff',
        borderRadius: 10,
        marginLeft: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
        elevation: 5,
      },
      modalBackdrop: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      modalContent: {
        width: '80%',
        padding: 20,
        backgroundColor: '#fff',
        borderRadius: 10,
        alignItems: 'center',
      },
      modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 20,
      },
      input: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        paddingVertical: 10,
        paddingHorizontal: 15,
        marginBottom: 20,
        width: '100%',
      },
      colorLabel: {
        fontSize: 16,
        marginBottom: 10,
      },
      colorList: {
        marginBottom: 20,
      },
      colorItem: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        marginRight: 10,
      },
      createButton: {
        width: '100%',
        paddingVertical: 15,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
      },
      createButtonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
      },
  });
  export default styles;
