const TEXTS = {
  HOME_TAB: 'Home',
  PROFILE_TAB: 'Profile',
  FAMILY_TAB: 'Family',
  //ADD_TAB: 'Add',
  QR_CODE_TAB: 'QR Code',
  REPORT_TAB: 'Report',
  MORE_TAB: 'More',
  EDIT_PROFILE: 'Edit Profile',
  LOGIN_WELCOME: 'Welcome back!',
  LOGIN_TITLE: 'Please type your credentials to login',
  EMAIL: 'Email address',
  EMAIL_PLACEHOLDER: 'Enter your email address',
  PASSWORD: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  REMEMBER_ME: 'Remember me',
  FORGOT_PASSWORD: 'Forget your Password?',
  FORGOT_PASSWORD_TITLE: 'Forgot your password?',
  FORGOT_PASSWORD_DESCRIPTION:
    'Please enter your email address to reset your password',
  SEND: 'Send',
  TRY_AGAIN: 'Try again',
  BACK_TO_LOGIN: 'Back to login',
  LOGIN: 'Login',
  LOGIN_OR: 'Or login with',
  LOGIN_WITH_GOOGLE: 'Login with Google',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  SIGNUP: 'Sign up',
  SIGNUP_WELCOME: 'Create an account!',
  SIGNUP_TITLE: 'Please type your credentials to sign up',
  TERMS_AND_CONDITIONS: 'I agree to the terms and conditions',
  HAVE_ACCOUNT: 'Already have an account?',
  PHONE_NUMBER: 'Phone number',
  PHONE: 'Phone',
  PHONE_PLACEHOLDER: '0000000000',
  PHONE_NUMBER_PLACEHOLDER: 'Enter your phone number',
  FIRST_NAME: 'First name',
  FIRST_NAME_PLACEHOLDER: 'Enter your first name',
  LAST_NAME: 'Last name',
  LAST_NAME_PLACEHOLDER: 'Enter your last name',
  FULL_NAME_PLACEHOLDER: 'Nguyen Van A',
  FULL_NAME_LABEL: 'Full Name',
  INVALID_EMAIL: 'Invalid email address',
  INVALID_PASSWORD: 'Password must be at least 6 characters long',
  EMAIL_REQUIRED: 'Email address is required',
  PASSWORD_REQUIRED: 'Password is required',
  FIRST_NAME_REQUIRED: 'First name is required',
  LAST_NAME_REQUIRED: 'Last name is required',
  PHONE_NUMBER_REQUIRED: 'Phone number is required',
  TERMS_AND_CONDITIONS_REQUIRED: 'You must agree to the terms and conditions',
  INVALID_PHONE_NUMBER: 'Invalid phone number',
  ADD_FAMILY_MEMBER_TITLE: 'Add Family Member',
  FAMILY_MEMBER_EMAIL_LABEL: 'Email',
  FAMILY_MEMBER_EMAIL_PLACEHOLDER: 'yourname@example.com',
  FAMILY_MEMBER_AGE_LABEL: 'Age',
  FAMILY_MEMBER_AGE_PLACEHOLDER: 'Choose age',
  FAMILY_MEMBER_RELATION: 'Enter Relation with Member',
  SELECT_COLOR_PLACEHOLDER: 'Select a color...',
  FAMILY_DETAIL: 'Family detail',
  ADD: 'Add',
  SELECT_COLOR_TITLE: `Select profile color`,
  PROFILE_NAME: 'TG',
  CONFIRM: 'Confirm',
  SELECT_PROFILE_COLOR_TITLE: 'Select profile color',
  SAVE: 'Save',
  FAMILY_MEMBERS_RELATION_LABEL: 'Relationship',
  FAMILY_MEMBERS_RELATION_PLACEHOLDER: 'Your relation with member',
  CREATE_FAMILY_TITLE: 'Create New Family',
  CREATE_FAMILY_NAME_LABEL: 'Family Name',
  CREATE_FAMILY_NAME_PLACEHOLDER: 'Enter family name',
  CREATE_FAMILY_SIZE_LABEL: 'Family Size',
  CREATE_FAMILY_SIZE_PLACEHOLDER: 'Choose family size',
  CREATE_FAMILY_LEADER_NAME_LABEL: 'Leader Name',
  CREATE_FAMILY_LEADER_NAME_PLACEHOLDER: 'Enter leader name',
  CREATE_FAMILY_LEADER_PHONE_LABEL: 'Leader Phone',
  CREATE_FAMILY_LEADER_PHONE_PLACEHOLDER: 'Enter leader phone',
  CREATE_FAMILY_LEADER_EMAIL_LABEL: 'Leader Email',
  CREATE_FAMILY_DESCRIPTION_LABEL: 'Description',
  CREATE_FAMILY_DESCRIPTION_PLACEHOLDER: 'Enter description',
  SELECT_FAMILY_COLOR_TITLE: 'Select family color',
  CHOOSE_COLOR: 'Choose Color',
  CREATE: 'Create',
  PACKAGE_TITLE: 'Choose the package',
  PURCHASED_TITLE: 'Purchased',
  PACKAGE_REGISTER: 'Register',
  NAME_REQUIRED: 'Name is required',
  AGE_REQUIRED: 'Age is required',
  RELATION_REQUIRED: 'Relation is required',
  DESCRIPTION_REQUIRED: 'Description is required',
  FAMILY_ID_REQUIRED: 'Family ID is required',
  FAMILY_ID_LABEL: 'Family ID',
  FAMILY_ID_PLACEHOLDER: 'Enter family ID',
  MEMBER: 'Member',

  EDIT_FAMILY_TITLE: 'Edit Family',
  EDIT_FAMILY_NAME_LABEL: 'Change Family Name',
  EDIT_FAMILY_NAME_PLACEHOLDER: 'Enter New Family Name',
  EDIT_FAMILY_DESCRIPTION_LABEL: 'Change Family Description',
  EDIT_FAMILY_DESCRIPTION_PLACEHOLDER: 'Enter New Family Description',
  PROFILE: 'Profile',
  PROFILE_DETAILS: 'Profile Details',
  CHANGE_PASSWORD: 'Change Password',
  LOGOUT: 'Logout',
};

export default TEXTS;
